import Head from 'next/head'
import { HeaderPage } from '@/components/Header/Header'
import { HomePage } from '@/components/Home/Home'
import { FooterPage } from '@/components/Footer/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Saphyr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <HeaderPage/>
    <HomePage/>
    <FooterPage/>

    </>
  )
}
