import Head from 'next/head'
import { HeaderPage } from '@/components/Header/Header'
import { PartnersPage } from '@/components/Partners/Partners'
import { FooterPage } from '@/components/Footer/Footer'


export default function Partners () {
    return (

    <>
     <Head>
        <title>Saphyr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <HeaderPage/> */}
        <PartnersPage/>
        <FooterPage/>
    </>


    )
}